- SSD_E.sln
- SSD_E/SSD_E.vcxproj
- SSD_E/SSD_E.vcxproj.filters
- SSD_E/main.cpp
- TestShellApplication-Test/TestShellApplication-Test.vcxproj
- TestShellApplication-Test/main.cpp
- TestShellApplication-Test/packages.config
- TestShellApplication-Test/test.cpp
- TestShellApplication/TestShellApplication.vcxproj
- TestShellApplication/TestShellApplication.vcxproj.filters
- TestShellApplication/main.cpp
- VirtualSSD-Test/VirtualSSD-Test.vcxproj
- VirtualSSD-Test/main.cpp
- VirtualSSD-Test/packages.config
- VirtualSSD-Test/pch.cpp
- VirtualSSD-Test/pch.h
- VirtualSSD-Test/test.cpp
- [Title] Project Init Pull request
- Add 2 main project: TestShellApplication, VirtualSSD
- Add 2 test project: TestShellApplication-Test, VirtualSSD-Test
> [feature][unittest] project init

- TestShellApplication/DriverInterface.h
- TestShellApplication/ReadCommand.cpp
- TestShellApplication/ReadCommand.h
- TestShellApplication/SSDCommand.cpp
- TestShellApplication/SSDCommand.h
- TestShellApplication/SSDDriver.cpp
- TestShellApplication/SSDDriver.h
- TestShellApplication/TestShellApplication.vcxproj
- TestShellApplication/TestShellApplication.vcxproj.filters
- TestShellApplication/WriteCommand.cpp
- TestShellApplication/WriteCommand.h
Shell Application의 Command Pattern을 적용을 위한 interface 및 Read/Write Command의 skeleton class 제작 PR 건 입니다.
> [feature][shell] Shell Application의 Command Pattern을 적용을 위한 Interface 및 Skeleton Code 작성 건

- TestShellApplication-Test/TestShellApplication-Test.vcxproj
- TestShellApplication-Test/test.cpp
SsdDeviceDriver 기본 클래스 및 테스트 Mock을 생성 했습니다.
> [feature][unittest] ssd device driver

- TestShellApplication-Test/test.cpp
- TestShellApplication/DriverInterface.h
- TestShellApplication/Shell.cpp
- TestShellApplication/Shell.h
- TestShellApplication/TestShellApplication.vcxproj
- TestShellApplication/TestShellApplication.vcxproj.filters
- TestShellApplication/main.cpp
Shell Test에서 Shell Class를 사용하여 TC를 제작할 수 있도록 기반이 되는 코드들을 추가하여 PR  올립니다.
> [feature][shell] Update TC to use Shell class.

- TestShellApplication-Test/SSDDriver_test.cpp
- TestShellApplication-Test/TestShellApplication-Test.vcxproj
- TestShellApplication-Test/test.cpp
- TestShellApplication/ReadCommand.cpp
- TestShellApplication/ReadCommand.h
- TestShellApplication/Shell.cpp
- TestShellApplication/Shell.h
> [feature][shell] implement TC_1 (ReadZeroTest)

- SSD_E/DeviceDriver.cpp
- SSD_E/DeviceDriver.h
- SSD_E/IOManager.cpp
- SSD_E/IOManager.h
- SSD_E/SSD_E.vcxproj
- SSD_E/SSD_E.vcxproj.filters
- SSD_E/main.cpp
- SSD_E/ssd.cpp
- SSD_E/ssd_interface.h
- VirtualSSD-Test/DeviceDriver_test.cpp
- VirtualSSD-Test/IOManager_test.cpp
- VirtualSSD-Test/VirtualSSD-Test.vcxproj
- VirtualSSD-Test/test.cpp
[feature/refactoring][Storage] Storage TDD 기반 Red&Green&Refactor 완료 PR의 건 입니다.
추가적인 업무로는 구조 Refactoring 및 TC 추가 예정입니다.
> [feature/refactoring][Storage] Storage TDD 기반 Red&Green&Refactor 완료 PR의 건

- TestShellApplication-Test/test.cpp
- TestShellApplication/ReadCommand.cpp
- TestShellApplication/ReadCommand.h
- TestShellApplication/SSDCommand.cpp
- TestShellApplication/SSDCommand.h
- TestShellApplication/SSDDriver.h
- TestShellApplication/Shell.cpp
- TestShellApplication/Shell.h
- TestShellApplication/WriteCommand.cpp
- TestShellApplication/WriteCommand.h
ReadCommand에 대한 Exception handling 관련 code입니다.
> [Feature/shellTestApp][ReadCommand] Read Exception handling

- TestShellApplication/ReadCommand.cpp
- TestShellApplication/ReadCommand.h
[refactor][ReadCommand] refactoring 완료건 PR입니다.
> [refactor][ReadCommand] refactoring 완료건 PR입니다.

- TestShellApplication-Test/test.cpp
- TestShellApplication/Shell.cpp
- TestShellApplication/WriteCommand.cpp
- TestShellApplication/WriteCommand.h
Shell의 "write" command에 대한 TC 추가 및 구현 건입니다.
> [shell] "write" command 추가 건

- SSD_E/FileManager.cpp
- SSD_E/SSD_E.vcxproj
- SSD_E/SSD_E.vcxproj.filters
- SSD_E/ssd.cpp
SSD의 Read, Write시에 사용되는 FileManager Module을 추가하였습니다.
> [feature][fileManager] Add FileManager Class for SSD

- TestShellApplication-Test/test.cpp
- TestShellApplication/Shell.cpp
full read command 구현 건입니다.
확인 부탁드립니다!
> [feature/shellTestApp] fullread command 구현 건입니다.

- TestShellApplication-Test/test.cpp
- TestShellApplication/FullWriteCommand.cpp
- TestShellApplication/FullWriteCommand.h
- TestShellApplication/SSDCommand.cpp
- TestShellApplication/SSDCommand.h
- TestShellApplication/Shell.cpp
- TestShellApplication/TestShellApplication.vcxproj
- TestShellApplication/TestShellApplication.vcxproj.filters
"fullwrite" command에 대한 TC 추가 및 구현 건 입니다.
> [Shell] "fullwrite" command 구현 건

- VirtualSSD-Test/DeviceDriver_test.cpp
[feature][unittest] 실제 ssd read write tc 추가 (write/read)
> [feature][unittest] 실제 ssd read write tc 추가

- TestShellApplication-Test/test.cpp
- TestShellApplication/Shell.cpp
- TestShellApplication/Shell.h
그 외 command (help, exit, invalid command)에 대한 처리 구현 건입니다.
> [Feature/shellTestApp_helpExitCommand] 그 외 Command 처리 구현 건

- SSD_E/FileManager.cpp
- SSD_E/IOManager.cpp
- SSD_E/IOManager.h
예시)
Command: R	LBA: 4
Command: W	LBA: 2	Data: 0xABCDABCD
Command: W	LBA: 0	Data: 0x00000001
Command: R	LBA: 0
Command: W	LBA: 5	Data: 0xABCDABCD
> [feature][Storage]SSD Log 추가 PR의 건

- TestShellApplication-Test/test.cpp
- TestShellApplication/FullReadCommand.cpp
- TestShellApplication/FullReadCommand.h
- TestShellApplication/FullWriteCommand.cpp
- TestShellApplication/FullWriteCommand.h
- TestShellApplication/ReadCommand.cpp
- TestShellApplication/ReadCommand.h
- TestShellApplication/SSDCommand.cpp
- TestShellApplication/SSDCommand.h
- TestShellApplication/SSDCommandInvoker.cpp
- TestShellApplication/SSDCommandInvoker.h
- TestShellApplication/Shell.cpp
- TestShellApplication/Shell.h
- TestShellApplication/TestShellApplication.vcxproj
- TestShellApplication/TestShellApplication.vcxproj.filters
- TestShellApplication/WriteCommand.cpp
- TestShellApplication/WriteCommand.h
shell의 command를 Pattern을 적용하도록 수정하였습니다.
신규 command 추가/삭제 시 invoker code를 수정하면 됩니다.
> [refactoring][shell] Command Pattern 적용

- TestShellApplication-Test/test.cpp
- TestShellApplication/ExitCommand.cpp
- TestShellApplication/ExitCommand.h
- TestShellApplication/HelpCommand.cpp
- TestShellApplication/HelpCommand.h
- TestShellApplication/InvalidCommand.cpp
- TestShellApplication/InvalidCommand.h
- TestShellApplication/SSDCommand.h
- TestShellApplication/SSDCommandInvoker.cpp
- TestShellApplication/SSDCommandInvoker.h
- TestShellApplication/Shell.cpp
- TestShellApplication/TestShellApplication.vcxproj
- TestShellApplication/TestShellApplication.vcxproj.filters
help 및  exit 2개의  command 추가한 PR 입니다.
#24 PR의 command pattern을 적용한 것으로 내용이 이어지는 PR 입니다.
> [feature][shell] "help" "exit" command 추가

- SSD_E/FileManager.cpp
- SSD_E/FileManager.h
- SSD_E/IOManager.cpp
- VirtualSSD-Test/DeviceDriver_test.cpp
> [hotfix][storage] merge 중 build err 유발되어 build fix.

- TestShellApplication-Test/SSDDriver_test.cpp
- TestShellApplication/SSDDriver.cpp
SSD driver --> ssd Interface 명령 포맷 변경 건 입니다.
리뷰 부탁드립니다.
> [hotfix][ssddriver] SSDDriver Connecting SSD format fix

- .gitignore
- SSD_E/DeviceDriver.cpp
- SSD_E/DeviceDriver.h
- SSD_E/IOManager.cpp
- SSD_E/IOManager.h
- SSD_E/SSD.h
- SSD_E/SSDCommand.cpp
- SSD_E/SSDCommand.h
- SSD_E/SSDInterface.h
- SSD_E/SSD_E.vcxproj
- SSD_E/SSD_E.vcxproj.filters
- SSD_E/ssd.cpp
- VirtualSSD-Test/DeviceDriver_test.cpp
Erase 기능 추가하며 Command Pattern 적용하였습니다.
> Add Erase feature & Apply Command Pattern

- SSD_E/SSDCommand.cpp
- SSD_E/SSDCommand.h
- SSD_E/SSDInterface.h
- TestShellApplication-Test/Runner_test.cpp
- TestShellApplication-Test/test.cpp
- TestShellApplication/Runner.cpp
- TestShellApplication/Shell.cpp
- TestShellApplication/Shell.h
- TestShellApplication/main.cpp
- VirtualSSD-Test/DeviceDriver_test.cpp
@JSynd 님께서 올려주신 PR-#41에서 아래 내용을 추가한 PR 입니다.
- Runner Class가 반영 안됨
- gtest의 Mock class 관련 build 안되던 것을 수정
> [fix][shell] Build Error 해결 건

- TestShellApplication-Test/test.cpp
- TestShellApplication/Shell.cpp
- TestShellApplication/Shell.h
- TestShellApplication/TestLibrary.cpp
- TestShellApplication/TestLibrary.h
- TestShellApplication/TestLibraryCommandInvoker.cpp
- TestShellApplication/TestLibraryCommandInvoker.h
- TestShellApplication/TestScripts/TestApp1.cpp
- TestShellApplication/TestScripts/TestApp1.h
- TestShellApplication/TestScripts/TestApp2.cpp
- TestShellApplication/TestScripts/TestApp2.h
- TestShellApplication/TestScripts/TestScriptBase.cpp
- TestShellApplication/TestScripts/TestScriptBase.h
- TestShellApplication/TestScripts/TestScriptInvoker.cpp
- TestShellApplication/TestScripts/TestScriptInvoker.h
- TestShellApplication/TestShellApplication.vcxproj
- TestShellApplication/TestShellApplication.vcxproj.filters
TestLibrary class와 Test Script class를 Commander Pattern + Invoker를 사용하도록 수정한 pr건입니다.
TestScript class + invoker는 dll로 빠질 예정입니다.
감사합니다.
> [Feature/shellTestApp_refactoring] 구조 변경 (Invoker 적용) 건 입니다.

- TestShellApplication-Test/Runner_test.cpp
- TestShellApplication-Test/SSDDriver_test.cpp
- TestShellApplication/SSDDriver.cpp
SSDDriver interface 변경에 따른 runner Test Mocking내용 변경 건입니다.
리뷰 부탁드립니다.
> [feature][runner] change ssd driver mocking based on Interface change

- TestShellApplication-Test/Runner_test.cpp
- TestShellApplication-Test/test.cpp
- TestShellApplication/CommandInterface.h
- TestShellApplication/Device.cpp
- TestShellApplication/Device.h
- TestShellApplication/DriverInterface.h
- TestShellApplication/EraseCommand.cpp
- TestShellApplication/EraseCommand.h
- TestShellApplication/FlushCommand.cpp
- TestShellApplication/FlushCommand.h
- TestShellApplication/ReadCommand.cpp
- TestShellApplication/SSDDriver.cpp
- TestShellApplication/SSDDriver.h
- TestShellApplication/Shell.cpp
- TestShellApplication/ShellException.cpp
- TestShellApplication/ShellException.h
- TestShellApplication/TestLibrary.cpp
- TestShellApplication/TestLibrary.h
- TestShellApplication/TestLibraryCommandInvoker.cpp
- TestShellApplication/TestShellApplication.vcxproj
- TestShellApplication/TestShellApplication.vcxproj.filters
- TestShellApplication/WriteCommand.cpp
아래 신규 Command관련 구현 건입니다.
- erase 
- erase_range
- flush
확인부탁드립니다.
> [Feature/shellTestApp_EraseFlushCommand] Shell command 추가구현건 입니다.

- SSD_E/BufferManager.cpp
- SSD_E/FileManager.cpp
- SSD_E/IOManager.cpp
교재에 명시된 최소한의 최적화만 지키게 설계했습니다.
완벽하게 하고 싶었으나.. 알고리즘 능력이 부족했네요.. :(
> Feature/optimize wb - Write Buffer 최적화 코드 PR 건입니다.

- TestShellApplication-Test/test.cpp
- TestShellApplication/Runner.cpp
- TestShellApplication/Shell.cpp
- TestShellApplication/Shell.h
- TestShellApplication/TestLibrary.cpp
- TestShellApplication/TestLibrary.h
- TestShellApplication/TestLibraryCommandInvoker.cpp
- TestShellApplication/TestLibraryCommandInvoker.h
- TestShellApplication/TestLibraryCommandInvokerInterface.h
- TestShellApplication/TestLibraryInterface.h
- TestShellApplication/TestScripts/TestApp1.cpp
- TestShellApplication/TestScripts/TestApp2.cpp
- TestShellApplication/TestScripts/TestScriptBase.cpp
- TestShellApplication/TestScripts/TestScriptBase.h
- TestShellApplication/TestScripts/TestScriptInterface.h
- TestShellApplication/TestScripts/TestScriptInvoker.cpp
- TestShellApplication/TestScripts/TestScriptInvoker.h
테스트 쉘 스크립트 모드 실행 시 다른 로그출력에 관련된 수정입니다.
리뷰 부탁드립니다!
> [feature][script_log] script running mode log implementation

- SSD_E.sln
- TestShellApplication/EraseCommand.cpp
- TestShellApplication/TestLibrary.cpp
- TestShellApplication/TestLibrary.h
해당 pr에서 2가지 관련 수정이 있습니다. 
1. Erase Command에서 LBA Range 관련 bug가 있어 수정했습니다.
(as-was) Erase {START_LBA} {MAX_LBA}일 경우 {MAX_LBA}에서 range error return
-> argument 확인 과정에서 exeption throw 하지 않고 Erase command 처리 과정 중에서
Erase range을 확인해서 SSD에게 요청하도록 수정.
2. Solution build 순서를 Dll -> TestApp 순서로 변경했습니다.
> [Feature/shell test app hotfix] Shell Test app 관련 bug 수정 건

- TestShellApplication/Device.cpp
- TestShellApplication/Device.h
- TestShellApplication/Shell.cpp
- TestShellApplication/TestLibrary.cpp
- TestShellApplication/TestLibrary.h
- TestShellApplication/TestLibraryCommandInvoker.cpp
- TestShellApplication/TestLibraryCommandInvoker.h
- TestShellApplication/TestLibraryCommandInvokerInterface.h
- TestShellApplication/TestLibraryInterface.h
- TestShellApplication/TestScripts/TestApp1.cpp
- TestShellApplication/TestScripts/TestApp2.cpp
해당 PR에는 2가지 수정사항이 포함되어있습니다.
1. TestLibrary에서 Commander Pattern + Invoker를 적용하면서
실행할 함수를 지정한 후에 execute 함수에 모든 인자를 전달하도록 했었는데
해당 부분에 대해서 Method chaining으로 readability를 높였습니다.
2. Device class를 여러번 호출할 경우는 현재 구조 상 없을 것으로 보이지만,,
Device 객체는 1개로 관리되는 것이 맞아보여 Singleton pattern을 적용했습니다.
> [Feature/ShellTestApp_Refactor]  TestLib & Device design pattern 적용 건입니다.

- TestScriptLib/TestScriptLib.vcxproj
- TestScriptLib/TestScriptLib.vcxproj.filters
- TestScriptLib/dllmain.cpp
- TestShellApplication-Test/TestShellApplication-Test.vcxproj
- TestShellApplication/TestScripts/FailTestApp.cpp
- TestShellApplication/TestScripts/FailTestApp.h
- VirtualSSD-Test/VirtualSSD-Test.vcxproj
아래 내용 추가합니다.
1. 실패하는 TestSciprt - "failtestapp" 추가
2. gtest의 release 모드에서 pre compiled header 사용 안하도록 옵션 수정
> [shell][runner] 실패하는 TestScript 추가건

- TestShellApplication/TestScripts/TestScriptInvoker.cpp
혁서님의 매의 눈으로 찾아낸 버그 수정사항입니다!
Shell Mode 일 때 종료 조건을 수정했습니다
> [feature][shell] shell mode scenario end condition fix
